### ISSUE TITLE
footer not at bottom of page

### ISSUE THREAD

**Issue by gkimbwala** [gkimbwala/MyCitizenReport#1]
need to get the footer at the bottom of page. probably via sticky footer wrapper.

**Comment by baroobob** [comment]
I'm on it.

**Comment by gkimbwala** [comment]
They are there now. I think that Geoff fixed them.

**Comment by baroobob** [comment]
They weren't when I started on this.  Just submitted my changes.

**Comment by gkimbwala** [comment]
cool!

**Comment by baroobob** [comment]
Closing this issue.
